servers:
  - host:
    authentication:
    ssh:
      user:
      password:
    nginx:
      log:
        access:
        error:
    environments:
      - name:
        value:
  - host:
    authentication:
    ssh:
      user:
      password:
    nginx:
      log:
        access:
        error:
    environments:
      - name:
        value:
