servers:
  - host:
    authentication:
    ssh:
      user:
      password:
    environments:
      - name:
        value:
  - host:
    authentication:
    ssh:
      user:
      password:
    environments:
      - name:
        value:
